services:
  - type: web
    name: miyzaabedu
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: MiyzaabEdu
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: miyzaabedu
          property: host
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: miyzaabedu-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: miyzaabedu-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: miyzaabedu-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: miyzaabedu-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: miyzaabedu-db
          property: password
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: file

databases:
  - name: miyzaabedu-db
    databaseName: miyzaabedu
    user: miyzaabedu
    plan: free
