services:
  - type: web
    name: miyzaabedu
    env: docker
    dockerfilePath: ./Dockerfile
    disk:
      name: miyzaabedu-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: APP_NAME
        value: MiyzaabEdu
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: miyzaabedu
          property: host
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/data/database.sqlite
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: file
